### ISSUE TITLE
The v2.2.0 branch dose not build with gcc-4.9.2

### ISSUE THREAD

**Issue by pank7** [gar1t/erlang-czmq#33]
I am building it in an updated archlinux box, and the error message says:

```shell
...
make[2]: Entering directory '/home/pank7/src/czmq/src'
  CC       zauth.lo
In file included from /usr/include/ctype.h:25:0,
                 from ../include/czmq_prelude.h:203,
                 from ../include/czmq.h:19,
                 from zauth.c:25:
/usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^
cc1: all warnings being treated as errors
Makefile:802: recipe for target 'zauth.lo' failed
make[2]: *** [zauth.lo] Error 1
...
```

I know the lastest `master` branch of `czmq` has already fixed this, but in my situation, I am trying to use it through `erlang-czmq`, which is using the v2.2.0 branch, so my question is are we planning on moving to a newer version of `czmq`?

**Comment by essen** [comment]
Seeing this exact same issue.

**Comment by wayann** [comment]
> I know the lastest `master` branch of `czmq` has already fixed this, but in my situation, I am trying to use it through `erlang-czmq`, which is using the v2.2.0 branch, so my question is are we planning on moving to a newer version of `czmq`?

I know I can locally copy czmq and change those errors... which is what I'm doing at the moment. just asking if nobody interested in a newer version of `czmq` ?
